### ISSUE TITLE
PermissionError on Windows when using the 'load' action with uploaded files

### ISSUE THREAD

**Issue by kenliit** [semente/django-smuggler#61]
I am using Windows python and Django.  Tried django-smuggler and found this issue:

Succeed on 'dump', and created file:  2018-04-27T11_05_53.741567.json

on a new database, tried '/admin/load', it did display a page and asking for the file. clicked the file that just saved, then clicked 'load' button. It shows an error: 

PermissionError at /admin/load/
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Ken\\AppData\\Local\\Temp\\repair_2018-04-27T15_44_57.883458_fz9nmkw9.json'

I notice that the file name has been changed during the process, but i don't know why?  or did I do anything wrong?

**Comment by jaap3** [comment]
I'm not sure, smuggler hasn't really been tested on windows as far as I known.

When you upload a fixture it is saved in a temporary directory and then it's loaded. For some reason on your system this file seems to be locked. Does this happen every time you try to load?

It's hard to reproduce/debug this issue without access to a Windows system, so a PR to demonstrate and fix this issue would be much appreciated. 

(Currently travis only runs on windows so that'll have to change as well).

**Comment by semente** [comment]
Hey, @ManiMozaffar and @kenliit! Sorry you are having this issue on Windows. As @jaap3 noted, it is hard for us debug this issue because we don't run a Windows environment so could you share the whole traceback output ?

It is not clear for me if the error happens on `load_fixtures()` or on `os.unlink()` (https://github.com/semente/django-smuggler/blob/master/smuggler/views.py#L149).

**Comment by semente** [comment]
It is possible that it is missing a `stream.close()` at https://github.com/semente/django-smuggler/blob/master/smuggler/utils.py#L69.

**Comment by jaap3** [comment]
Temporary files are created here:
https://github.com/semente/django-smuggler/blob/524b99f1de8cb981ee5a313a605282a6bf29c16e/smuggler/views.py#L113

They are written here:
https://github.com/semente/django-smuggler/blob/524b99f1de8cb981ee5a313a605282a6bf29c16e/smuggler/utils.py#L19

Removed here:
https://github.com/semente/django-smuggler/blob/524b99f1de8cb981ee5a313a605282a6bf29c16e/smuggler/views.py#L152

I think the issues is related to the **creation** of the temporary files. `mkstemp` returns a tuple of two values a file pointer and a path (https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp), smuggler ignores the first one and always uses a path.

However, the file pointer is similar to an open file.

I found this Stack Overflow answer which probably contains the correct solution:

https://stackoverflow.com/questions/34716996/cant-remove-a-file-which-created-by-tempfile-mkstemp-on-windows

It would be greatly appreciated if someone with access to a Windows computer can test this fix and make a pull request.

**Comment by jaap3** [comment]
I created a pull request, but cannot test if this is actually the correct solution.

**Comment by semente** [comment]
good catch @jaap3!
